### ISSUE TITLE
Error in executing in command line

### ISSUE THREAD

**Issue by BALUSANGEM** [Vishnubalu/tic_tac_toe-game#1]
@Vishnubalu I am trying to execute your project from command line and it is showing following error

<img width="442" alt="Screen Shot 2019-03-16 at 2 34 13 PM" src="https://user-images.githubusercontent.com/15178098/54473049-b2e00c80-47f8-11e9-8be0-eec3058de2ef.png">

**Comment by Vishnubalu** [comment]
Make sure that you are using python 3.5 or python 3.6
